controller_joint_names: ['', 'r_kuan_joint', 'r_kuan2_joint', 'r_thigh_joint', 'r_calf_joint', 'r_ankle_joint', 'r_foot_joint', 'l_kuan_joint', 'l_kuan2_joint', 'l_thigh_joint', 'l_calf_joint', 'l_ankle_joint', 'l_foot_joint', ]
